config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'page/home'
  root to: 'page#home'

  resources :users, only: [:show, :edit, :update] do resources :posts
  resources :followers, only: :index
  resources :following, only: :index
  end
  resources :posts do
    resources :likes
  end
  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :feed_posts, only: :index
  resources :comments, only: [:create]
  resources :authentications, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :following, class_name: "User", foreign_key: "following_id"
  validates :follower_id, uniqueness: {scope: :following_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :content, presence: true, length: {maximum: 140}
  validates :image_data, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  has_many :follower_follows, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :following_follows, source: :following

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  validates :name, presence: true, length: {maximum: 40}
  validates :email, presence: true, uniqueness:  { case_sensitive: false},
            format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def apply_omniauth(auth)
    update_attributes(
        provider: auth.provider,
        uid: auth.uid
    )
  end

  def has_facebook_linked?
    self.provider.present? && self.uid.present?
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def index
    @user = User.find(params[:id])
    @follower = @user.followers
    @followings = @user.followings
  end

  def create
    follower_user = current_user
    following_user = User.find(params[:following_id])
    @follow = Follow.new(follower: follower_user, following: following_user)
    if @follow.valid?
      @follow.save
      redirect_to user_path(following_user), flash: {success:"You follow now"}
    else
      redirect_to user_path(following_user), flash: {alert: "You already follow"}
    end
  end

  def destroy
    follow = Follow.find_by(follower_id: current_user.id, following_id: params[:user_id])
    if follow.present?
      follow.destroy
        flash.now[:notice] = "Successfully deleted follow!"
        redirect_to user_path
    else
      flash[:alert] = "Error delete follow!"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :find_post

  def create
    @like = Like.new(likes_params)
      if @like.save
        redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
      end
  end

  def destroy
    liked = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    if liked.present?
      if liked.destroy
        flash.now[:notice] = 'Successfully deleted Like!'
        redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
      else
        flash[:alert] = 'Error delete Like!'
      end
    end
  end

  private
  def likes_params
    params.permit(:user_id, :post_id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @posts = Post.all.order(created_at: :desc)
    if !user_signed_in?
      redirect_to new_user_session_path

    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :load_user

  def index
    @posts = @user.posts.order(created_at: :desc)
    @follower = @user.followers
    @followings = @user.followings
  end

  def show
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = @user
    if @post.valid?
      @post.image_derivatives! if @post.image_changed?
      @post.save
      redirect_to user_post_path(@user, @post)
    else
      render 'new', flash: { alert: 'Some error' }
    end
  end

  def edit
    @post = @user.posts.find(params[:id])
  end

  def update
    @post = @user.posts.find(params[:id])
    if @post.valid?
      @post.update(post_params)
      redirect_to user_post_path(@user, @post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    if @post.destroy
      flash.now[:notice] = 'Successfully deleted post!'
      redirect_to user_path(current_user)
    else
      flash[:alert] = 'Error updating post!'
    end
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :user_id)
  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    if current_user.present?
      current_user.apply_omniauth(request.env["omniauth.auth"])
      redirect_to edit_user_registration_path, notice: "Facebook Account Linked!"
    else
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user

  def show
    @posts = @user.posts.order(created_at: :desc)
    @follower = @user.followers
    @followings = @user.followings
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to edit_user_path(current_user)
  end

  private
  def user_params
    params.require(:user).permit(
        :username, :name, :website, :bio, :email, :phone, :gender, :image)
  end

  def load_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feed_posts_helper.rb
module FeedPostsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-3">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#edit-profile" role="tab" aria-controls="edit-profile" aria-selected="true">Edit Profile</a>
        <a class="nav-link" id="change-password-tab" data-toggle="pill" href="#change-password" role="tab" aria-controls="change-password" aria-selected="false"> Edit Password</a>
        <a class="nav-link" id="change-avatar" data-toggle="pill" href="#change-avatar" role="tab" aria-controls="change-avatar" aria-selected="false">Change Avatar</a>
        <a class="nav-link" id="push-message-tab" data-toggle="pill" href="#push-message" role="tab" aria-controls="push-message" aria-selected="false">Push-message</a>
      </div>
    </div>
    <div class="col-9">
      <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="edit-profile"  role="tabpanel" aria-labelledby="edit-profile-tab">
          <div class="row">
            <%= form_with model: current_user, local: true do |f| %>
              <table class="table">
                <tbody>
                <tr>
                  <% if @user.image_data? %>
                    <th scope="row"> <%= image_tag @user.image_url, class: 'ava-edit-page' %></th>
                    <% else %>
                    <th scope="row"><%= image_tag "ava_default.png", class: 'ava-edit-page'%></th>
                  <% end %>
                  <td><p class="username"><b><%=current_user.username %></b></p>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Change Avatar: </th>
                  <td><%= f.file_field :image %></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :name %></th>
                  <td><%= f.text_field :name %></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :username %></th>
                  <td><%= f.text_field :username %></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :website %></th>
                  <td><%= f.text_field :website %></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :bio%></th>
                  <td><%= f.text_area :bio%></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :email %></th>
                  <td><%= f.text_field :email %></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :phone%></th>
                  <td><%= f.text_field :phone%></td>
                </tr>
                <tr>
                  <th scope="row"><%= f.label :gender%></th>
                  <td><%= f.text_field :gender %></td>
                </tr>
                <tr>
                  <td colspan="2"><%= f.submit "Save"%></td>
                </tr>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="change-password" role="tabpanel" aria-labelledby="change-password-tab">
          <p><a class="btn" <%= link_to 'Edit Password', edit_user_password_path  %></p>
        </div>
        <div class="tab-pane fade" id="change-avatar" role="tabpanel" aria-labelledby="change-avatar">

        </div>
        <div class="tab-pane fade" id="push-message" role="tabpanel" aria-labelledby="push-message-tab">3
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row profile">
  <div class="col-6 avatar">
    <% if @user.image_data? %>
      <div class="row"> <%= image_tag @user.image_url, class: 'ava'  %></div>
    <% else %>
      <div class="row"><%= image_tag "ava_default.png", class: 'ava'%></div>
    <% end %>
  </div>
  <div class="info col-6">
    <div class="user-info-box">
      <h2 class="username"><%= @user.username %></h2>
      <% if current_user == @user %>
        <a class="btn btn-primary" <%= link_to 'Edit Profile', edit_user_path(@user)  %>
        <% else %>
          <%if follower= Follow.find_by(follower_id: current_user.id, following_id: @user.id).present? %>
          <%= link_to "UnFollow", follow_path(user_id: @user.id), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-primary" %>
        <% elsif current_user.present? && current_user != @user%>
              <a class="btn btn-primary" <%= link_to("Follow", follows_path(following_id: @user.id), method: :post) %>
            <%else %>
            <%= link_to "UnFollow", follow_path(user_id: @user.id), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-primary" %>
        <% end %>
      <% end %>
    </div>

    <div class="posts-block d-flex">
      <ul>
        <li><%= @posts.count %> posts</li>
          <% if @user.followers.count.nil? %>
            0 followers
          <% else %>
            <li><%= link_to "#{@user.followers.count} followers", user_followers_path(@user) %> </li>
          <% end %>
          <% if @user.followings.count.nil? %>
            0 following
          <% else %>
            <li><%= link_to "#{@user.followings.count} following", user_following_index_path(@user) %> </li>
          <% end %>
      </ul>
    </div>
    <div class="full-name-block d-flex">
      <h2 class="name">Name: <%= @user.name %></h2>
       web: <%= @user.website %>
    </div>
  </div>
</div>

<div>
  <div class="user-blocks">
  <%= link_to "Posts", user_posts_path(@user), class:"table active" %>
    <a class="table" href="#">
      IGTV
    </a>
    <a class="table" href="#">
      SAVED
    </a>
    <a class="table" href="#">
      TAGGED
    </a>
  </div>

    <div class="row">
      <div class="row show-posts col-12">
        <% @posts.each do |post|%>
          <div class="posts-in-wall col-4 ">
            <% if post.image_data? %>
            <%=link_to (image_tag post.image_url(:small)), user_post_path(@user,post) %>
            <% end %>
            <%= post.content %><br/>
          </div>
        <% end %>
      </div>
    </div>
</div>
</div>