config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'page/home'
  root to: 'page#home'

  resources :users, only: [:show, :edit, :update] do resources :posts
  resources :followers, only: :index
  resources :following, only: :index
  end
  resources :posts do
    resources :likes
  end
  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :feed_posts, only: :index
  resources :comments, only: [:create]
  resources :authentications, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :following, class_name: "User", foreign_key: "following_id"
  validates :follower_id, uniqueness: {scope: :following_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :content, presence: true, length: {maximum: 140}
  validates :image_data, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  has_many :follower_follows, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :following_follows, source: :following

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  validates :name, presence: true, length: {maximum: 40}
  validates :email, presence: true, uniqueness:  { case_sensitive: false},
            format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def apply_omniauth(auth)
    update_attributes(
        provider: auth.provider,
        uid: auth.uid
    )
  end

  def has_facebook_linked?
    self.provider.present? && self.uid.present?
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def index
    @user = User.find(params[:id])
    @follower = @user.followers
    @followings = @user.followings
  end

  def create
    follower_user = current_user
    following_user = User.find(params[:following_id])
    @follow = Follow.new(follower: follower_user, following: following_user)
    if @follow.valid?
      @follow.save
      redirect_to user_path(following_user), flash: {success:"You follow now"}
    else
      redirect_to user_path(following_user), flash: {alert: "You already follow"}
    end
  end

  def destroy
    follow = Follow.find_by(follower_id: current_user.id, following_id: params[:user_id])
    if follow.present?
      follow.destroy
        flash.now[:notice] = "Successfully deleted follow!"
        redirect_to user_path
    else
      flash[:alert] = "Error delete follow!"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :find_post

  def create
    @like = Like.new(likes_params)
      if @like.save
        redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
      end
  end

  def destroy
    liked = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    if liked.present?
      if liked.destroy
        flash.now[:notice] = 'Successfully deleted Like!'
        redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
      else
        flash[:alert] = 'Error delete Like!'
      end
    end
  end

  private
  def likes_params
    params.permit(:user_id, :post_id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @posts = Post.all.order(created_at: :desc)
    if !user_signed_in?
      redirect_to new_user_session_path

    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :load_user

  def index
    @posts = @user.posts.order(created_at: :desc)
    @follower = @user.followers
    @followings = @user.followings
  end

  def show
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = @user
    if @post.valid?
      @post.image_derivatives! if @post.image_changed?
      @post.save
      redirect_to user_post_path(@user, @post)
    else
      render 'new', flash: { alert: 'Some error' }
    end
  end

  def edit
    @post = @user.posts.find(params[:id])
  end

  def update
    @post = @user.posts.find(params[:id])
    if @post.valid?
      @post.update(post_params)
      redirect_to user_post_path(@user, @post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    if @post.destroy
      flash.now[:notice] = 'Successfully deleted post!'
      redirect_to user_path(current_user)
    else
      flash[:alert] = 'Error updating post!'
    end
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :user_id)
  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user

  def show
    @posts = @user.posts.order(created_at: :desc)
    @follower = @user.followers
    @followings = @user.followings
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to edit_user_path(current_user)
  end

  private
  def user_params
    params.require(:user).permit(
        :username, :name, :website, :bio, :email, :phone, :gender, :image)
  end

  def load_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feed_posts_helper.rb
module FeedPostsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="container" >
  <div class="row">
    <div class="row input-form">
      <%= form_for [@user,@post] do |form| %>
        <div class="field"><br/>
          <b><%= form.label :content, 'Content' %></b><br/>
          <%= form.text_area :content, size: "50x2", placeholder: 'Enter you describe, only 140 symbol' %><br/>
        </div>
        <div class="field">
          <%= form.hidden_field :image, value: @post.cached_image_data %>
          <%= form.file_field :image %>
        </div><br/>
        <%= form.text_field :user_id, value: @user.id, class:'d-none' %>
        <div>
          <%= form.submit 'Save Post', class: 'btn btn-primary' %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h3 class="row justify-content-center">Edit Post</h3>
<%= render 'shared/errors', object: @post  %>
<div class="container" >
  <div class="row">
    <div class="row input-form">
      <%= form_for [@user,@post] do |form| %>
        <div class="field"><br/>
          <b><%= form.label :content, 'Content' %></b><br/>
          <%= form.text_area :content, size: "50x2", placeholder: 'Enter you describe, only 140 symbol' %><br/>
        </div>
        <%= form.text_field :user_id, value: @user.id, class:'d-none' %>
        <div>
          <%= form.submit 'Save Post', class: 'btn btn-primary' %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="row show-posts">
        <% if @posts.present? %>
          <% @posts.each do |post|%>
            <div class="col-8">
              <%=link_to post.user.username, user_posts_path(post.user_id) %>
              posted:<br/>
              <%=link_to (image_tag post.image_url(:large)), user_post_path(post.user_id,post.id) %>
              <%= post.content %><br/>
            </div>
          <% end %>
        <% else %>
          <div class="side-right">No post found in subscriber</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h3 class="row justify-content-center">Add Post</h3>
  <%= render 'shared/errors', object: @post  %>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row col-12 post-view-form">
    <div class="col-8">
      <p class="left-item">
        <% if current_user == @post.user %>
          <%= link_to "Edit", edit_user_post_path(@user,@post), class:"button" %> |
          <%= link_to "Delete", user_post_path(@user,@post),
                      method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
        <% end %>
          <%= image_tag @post.image_url(:large)%><br/>
      </p>

      <div class="post-user-info">
        <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%>
        <%if is_like= Like.find_by(user_id: current_user.id, post_id: @post.id).present? %>
          <%= link_to "UnLike", post_like_path(user_id: current_user.id, post_id: @post.id), method: :delete %>
        <% else %>
          <%= link_to 'Like', post_likes_path(user_id: current_user.id, post_id: @post.id), method: :post %>
       <% end %></p>

        <b><%= @post.user.name %></b> <p class="create_data"> at <%= @post.created_at %></p>
        write:
        <%= @post.content %>
      </div>
    </div>

      <div class="post-view-right col-4">
        <div class="show-comments">
          <% if @post.comments.present? %>
            <% @post.comments.each do |c| %>
                  <p><b><%= c.user.name %> </b> :
                  <%= c.context %></p>
            <% end %>
            <%else %>
              No comment yet
          <% end %>
          </div>

        <div class="comment-input-form"><br/>
          <%= form_for [@comment] do |form| %>
            <%= form.text_area :context, placeholder: "write comment here", class:'input-field'%>
            <%= form.text_field :user_id, value: @user.id, class:'d-none' %>
            <%= form.text_field :post_id, value: @post.id, class:'d-none' %>
            <%= form.submit 'Send', class: 'btn btn-primary' %>
          <%end%>
        </div>
      </div>
  </div>
</div>