config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'page/home'
  root to: 'page#home'

  resources :users, only: [:show, :edit, :update] do resources :posts
  resources :followers, only: :index
  resources :following, only: :index
  end
  resources :posts do
    resources :likes
  end
  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  resources :feed_posts, only: :index
  resources :comments, only: [:create]
  resources :authentications, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :following, class_name: "User", foreign_key: "following_id"
  validates :follower_id, uniqueness: {scope: :following_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :content, presence: true, length: {maximum: 140}
  validates :image_data, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  has_many :follower_follows, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :following_follows, source: :following

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  validates :name, presence: true, length: {maximum: 40}
  validates :email, presence: true, uniqueness:  { case_sensitive: false},
            format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def apply_omniauth(auth)
    update_attributes(
        provider: auth.provider,
        uid: auth.uid
    )
  end

  def has_facebook_linked?
    self.provider.present? && self.uid.present?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :find_post

  def create
    @like = Like.new(likes_params)
      if @like.save
        redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
      end
  end

  def destroy
    liked = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    if liked.present?
      if liked.destroy
        flash.now[:notice] = 'Successfully deleted Like!'
        redirect_to user_post_path(user_id: @post.user_id, id: @post.id)
      else
        flash[:alert] = 'Error delete Like!'
      end
    end
  end

  private
  def likes_params
    params.permit(:user_id, :post_id)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @posts = Post.all.order(created_at: :desc)
    if !user_signed_in?
      redirect_to new_user_session_path

    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :load_user

  def index
    @posts = @user.posts.order(created_at: :desc)
    @follower = @user.followers
    @followings = @user.followings
  end

  def show
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = @user
    if @post.valid?
      @post.image_derivatives! if @post.image_changed?
      @post.save
      redirect_to user_post_path(@user, @post)
    else
      render 'new', flash: { alert: 'Some error' }
    end
  end

  def edit
    @post = @user.posts.find(params[:id])
  end

  def update
    @post = @user.posts.find(params[:id])
    if @post.valid?
      @post.update(post_params)
      redirect_to user_post_path(@user, @post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    if @post.destroy
      flash.now[:notice] = 'Successfully deleted post!'
      redirect_to user_path(current_user)
    else
      flash[:alert] = 'Error updating post!'
    end
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :user_id)
  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feed_posts_helper.rb
module FeedPostsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="container footer navbar-fixed-bottom row-fluid">
  <nav class="navbar d-flex">
    <ul>
      <li>ABOUT</li>
      <li>HELP</li>
      <li>PRESS</li>
      <li>API</li>
      <li>JOBS</li>
      <li>PRIVACY</li>
      <li>TERMS</li>
      <li>LOCATIONS</li>
      <li>TOP ACCOUNTS</li>
      <li>HASHTAGS</li>
      <li>LANGUAGE</li>
    </ul> <br>
    <p> © 2020 TWIGRAM FROM POKERFACE</p>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "Twigram", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="form-inline my-2 my-lg-0 ml-md-auto">
        <input class="form-control mr-sm-2" type="search" placeholder="@ Search" aria-label="Search">
      </form>
      <ul class="navbar-nav mr-auto ml-md-auto">
        <li class="nav-item">
          <%= link_to "Feed", feed_posts_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Notification</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Create post", new_user_post_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%=link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twigram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/header' if current_user %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render '/layouts/footer' %>
  </body>
</html>

app/views/page/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="row show-posts">
        <% @posts.each do |post|%>
          <div class="col-4"><br/>
            <%=link_to post.user.name, user_path(post.user_id) %>
            posted:<br/>
            <%= post.content.truncate_words(5) %><br/>
            <%=link_to (image_tag post.image_url(:small)), user_post_path(post.user_id,post.id) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="row justify-content-center">
  <% if object.errors.any? %>
    <ul>
      <h6>The following errors were found:</h6>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>